{"name": "test_login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <scripts.test_login.TestLogin object at 0x03307718>, username = 'itheima_test', password = 'ithema'\n\n    def test_login(self, username=\"itheima_test\", password=\"ithema\"):\n    \n        # 调用组合登录方法\n        self.pagelogin.page_login(username, password)\n        # 获取用户名\n>       msg = self.pagelogin.page_get_username()\n\nscripts\\test_login.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npage\\page_login.py:36: in page_get_username\n    self.base_get_element_info(page.login_get_username)\nbase\\base.py:29: in base_get_element_info\n    return self.base_find_element(loc).text\nbase\\base.py:15: in base_find_element\n    return WebDriverWait(self.driver,\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f7c47775-f054-478c-bf2f-8ef188499278\")>\nmethod = <function Base.base_find_element.<locals>.<lambda> at 0x03113F58>, message = ''\n\n    def until(self, method, message=''):\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value is not False.\"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.time() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, 'screen', None)\n                stacktrace = getattr(exc, 'stacktrace', None)\n            time.sleep(self._poll)\n            if time.time() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nc:\\users\\administrator\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:80: TimeoutException"}, "start": 1614408814275, "stop": 1614408861394, "uuid": "a5dee65e-ddaa-4093-8f26-ba71d60dcd7e", "historyId": "161da9f82071fb37eae9201ae900aa4f", "testCaseId": "1d80d88536c622141c7393804df49bc9", "fullName": "scripts.test_login.TestLogin#test_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "USER-20191018KD"}, {"name": "thread", "value": "8400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_login"}]}